# Generated by Django 2.2 on 2019-06-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='editable',
            field=models.BooleanField(default=False),
        ),
    ]
