# Generated by Django 2.2 on 2019-06-13 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='data_published',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
