# Generated by Django 2.2 on 2019-06-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190613_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='relevance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
