# Generated by Django 2.2 on 2019-06-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_relevance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='relevance',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
