# Generated by Django 2.2 on 2019-06-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20190614_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_published',
            field=models.DateField(auto_now_add=True),
        ),
    ]
