# Generated by Django 2.2 on 2019-06-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20190616_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
