# Generated by Django 2.2 on 2019-06-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20190616_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_published',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
