# Generated by Django 2.2 on 2019-05-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0004_auto_20190524_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=255),
        ),
    ]
