# Generated by Django 2.2 on 2019-05-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0002_auto_20190507_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='contatos',
            field=models.ManyToManyField(blank=True, null=True, related_name='_perfil_contatos_+', to='rede.Perfil'),
        ),
    ]
