# Generated by Django 2.2 on 2019-05-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0003_auto_20190507_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='contatos',
            field=models.ManyToManyField(related_name='_perfil_contatos_+', to='rede.Perfil'),
        ),
    ]
