# Generated by Django 2.2 on 2019-05-09 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0005_auto_20190509_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reacao',
            name='peso',
            field=models.IntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='reacao',
            name='postagem',
        ),
        migrations.AddField(
            model_name='reacao',
            name='postagem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rede.Postagem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reacao',
            name='tipo',
            field=models.CharField(choices=[('C', 'curtir'), ('A', 'amar'), ('R', 'rir'), ('I', 'se impressionar'), ('T', 'ficar triste'), ('B', 'ficar bravo')], default='C', max_length=1, null=True),
        ),
    ]
