# Generated by Django 2.2 on 2019-05-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0002_auto_20190517_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={},
        ),
    ]
