# Generated by Django 2.2 on 2019-04-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_person_midle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'short'), ('M', 'medium'), ('L', 'large')], max_length=1, null=True),
        ),
    ]
