# Generated by Django 2.2 on 2019-04-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_cpf_pessoafisica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(db_column='birth_city', max_length=50),
        ),
    ]
