# Generated by Django 2.2 on 2019-04-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20190423_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacter',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
