# Generated by Django 2.2 on 2019-04-23 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_blog_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='name',
            new_name='descricao',
        ),
    ]
