# Generated by Django 2.2 on 2019-04-23 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20190423_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='myapp.Categoria'),
        ),
    ]
