# Generated by Django 2.2 on 2019-04-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20190430_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='myapp.Blog'),
        ),
    ]
