# Generated by Django 2.2 on 2019-05-03 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20190503_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='inviter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='membership_invites', to='myapp.Person2'),
            preserve_default=False,
        ),
    ]
