# Generated by Django 2.2 on 2019-05-17 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Interessado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=12)),
                ('advogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processo.Advogado')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=255)),
                ('data_validade', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('ativo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('texto', models.CharField(max_length=255)),
                ('interessados', models.ManyToManyField(to='processo.Interessado')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processo.Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Apensamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_apensamento', models.DateField(auto_now_add=True)),
                ('processo_apensado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processo_apenssado', to='processo.Processo')),
                ('processo_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processo_original', to='processo.Processo')),
            ],
        ),
        migrations.AddField(
            model_name='advogado',
            name='registro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='processo.Registro'),
        ),
    ]
